import { UserData } from "@/types";

// Default fallback data
export const defaultUserData: UserData = {
  name: "Yasmin Azizah",
  faceShape: "Kotak",
  bodyShape: "Hourglass",
  colorTone: "Cool Winter",
  bmi: {
    value: 51.18,
    category: "Ideal",
    desc: "Badan kamu bagus ideal!"
  },
  celebrityMatch: {
    name: "Cut Syifa",
    matchPercentage: 88,
    imageUrl: "https://placehold.co/400/f0f0f0/333?text=Selebriti",
    reason: [
      "Kamu punya Rahang tegas dan kuat",
      "Dahi dan rahang memiliki lebar yang hampir sama",
      "Panjang dan lebar wajah hampir seimbang",
    ],
    description: "Cut Syifa adalah seorang aktris dan model Indonesia.",
  },
  faceShapeAnalysis: {
    uniqueFact:
      "Bentuk wajah kamu itu kotak! Kamu punya garis rahang yang tegas dan dahi nggak terlalu lebar atau sempit.",
    karakteristik: 
      "Kamu punya Rahang tegas dan kuat Dahi dan rahang memiliki lebar yang hampir sama Panjang dan lebar wajah hampir seimbang",
  },
  bodyShapeAnalysis: {
    imageUrl: "https://placehold.co/250x500/FFFFFF/CCCCCC?text=Bentuk+Tubuh",
    description:
      "Bagian Tengah Tubuhmu Lebih Dominan, Dengan Bagian Tengah Yang Lebih Menonjol Dan Bahu Yang Lebar Serta Bagian Dada Yang Penuh.",
    karakteristik:
      "Kamu punya Rahang tegas dan kuat -Dahi dan rahang memiliki lebar yang hampir sama Panjang dan lebar wajah hampir seimbang",
  },
  colorToneAnalysis: {
    description:
      "Ini berarti kulitmu memiliki undertone dingin dengan hint biru atau pink yang memberikan kesan elegan.",
    bestColors: [
      "#C7D2FE",
      "#BFDBFE",
      "#E0E7FF",
      "#E5E7EB",
      "#F472B6",
      "#60A5FA",
    ],
    neutralColors: [
      "#A3A3A3",
      "#6B7280",
      "#9CA3AF",
      "#D1D5DB",
      "#F59E0B",
      "#FACC15",
    ],
    worstColors: [
      "#F59E0B",
      "#FACC15",
      "#FEF08A",
      "#FDE68A",
      "#C7D2FE",
      "#BFDBFE",
    ],
    combination: [
      ["#F472B6", "#60A5FA"],
      ["#3B82F6", "#1E3A8A"],
      ["#C7D2FE", "#BFDBFE"],
    ],
    tips: {
      makeup: ["Kamu punya Rahang tegas dan kuat"],
      outfit: ["Kamu punya Rahang tegas dan kuat"],
      personality: ["Kamu punya Rahang tegas dan kuat"],
      karakteristik: ["Kamu punya Rahang tegas dan kuat"],
    },
  },
  conclusionTips: {
    face: [
      "Kamu punya Rahang tegas dan kuat",
      "Dahi dan rahang memiliki lebar yang hampir sama",
      "Panjang dan lebar wajah hampir seimbang",
    ],
    body: [
      "Kamu punya Rahang tegas dan kuat",
      "Dahi dan rahang memiliki lebar yang hampir sama",
      "Panjang dan lebar wajah hampir seimbang",
    ],
    color: [
      "Kamu punya Rahang tegas dan kuat",
      "Dahi dan rahang memiliki lebar yang hampir sama",
      "Panjang dan lebar wajah hampir seimbang",
    ],
    quickRecap: [
      "Kamu punya Rahang tegas dan kuat",
      "Dahi dan rahang memiliki lebar yang hampir sama",
      "Panjang dan lebar wajah hampir seimbang",
    ],
  },
};

export const analysisTabs = [
  { id: "shape", text: "Shape", icon: "/overview-ai/icons/ri_shape-fill.svg" },
  { id: "color", text: "Color Tone", icon: "/overview-ai/icons/mdi_color.svg" },
  { id: "body", text: "Body", icon: "/overview-ai/icons/healthicons_body.svg" },
  {
    id: "celebrity",
    text: "Celebrity Match",
    icon: "/overview-ai/icons/material-symbols_crown-rounded.svg",
  },
  {
    id: "tips",
    text: "Tips & Trick",
    icon: "/overview-ai/icons/ic_baseline-tips-and-updates.svg",
  },
];

export const hijabProducts = [
  {
    id: 1,
    image: "/hijab-1.png",
    match: "67% Match",
    matchIcon: "/overview-ai/icons/ai-generate.svg",
    matchAlt: "Heart",
    star: 4.6,
    starIcon: "/overview-ai/icons/material-symbols_star-rounded.svg",
    title: "Fay Hijab Sporty",
    price: "Rp49.000",
    oldPrice: "Rp99.000",
    heartIcon: "/overview-ai/icons/mdi_heart.svg",
    heartAlt: "Heart",
    reviews: 432,
    colorRecommendations: [
      { color: "bg-purple-600", border: "border-2 border-gray-300" },
      { color: "bg-blue-900" },
      { color: "bg-gray-800" },
    ],
    size: "XS-XXL",
    reason: "Perfect untuk bentuk wajah kotak dengan warna cool undertone",
  },
  {
    id: 2,
    image: "/overview-ai/model-hijab.png",
    match: "67% Match",
    matchIcon: "/overview-ai/icons/ai-generate.svg",
    matchAlt: "Heart",
    star: 4.6,
    starIcon: "/overview-ai/icons/material-symbols_star-rounded.svg",
    title: "Alana Bergo Jersey",
    price: "Rp75.000",
    oldPrice: "Rp99.000",
    heartIcon: "/overview-ai/icons/mdi_heart.svg",
    heartAlt: "Heart",
    reviews: 432,
    colorRecommendations: [
      { color: "bg-blue-900", border: "border-2 border-gray-300" },
      { color: "bg-purple-600" },
      { color: "bg-gray-800" },
    ],
    size: "XS-XXL",
    reason: "Perfect untuk bentuk wajah kotak dengan warna cool undertone",
  },
  {
    id: 3,
    image: "/hijab-3.png",
    match: "67% Match",
    matchIcon: "/overview-ai/icons/ai-generate.svg",
    matchAlt: "Heart",
    star: 4.6,
    starIcon: "/overview-ai/icons/material-symbols_star-rounded.svg",
    title: "Hijab Bergo",
    price: "Rp55.000",
    oldPrice: "Rp99.000",
    heartIcon: "/overview-ai/icons/mdi_heart.svg",
    heartAlt: "Heart",
    reviews: 432,
    colorRecommendations: [
      { color: "bg-teal-600", border: "border-2 border-gray-300" },
      { color: "bg-blue-900" },
      { color: "bg-gray-800" },
    ],
    size: "XS-XXL",
    reason: "Perfect untuk bentuk wajah kotak dengan warna cool undertone",
  },
  {
    id: 4,
    image: "/hijab-5.jpg",
    match: "67% Match",
    matchIcon: "/overview-ai/icons/ai-generate.svg",
    matchAlt: "Heart",
    star: 4.6,
    starIcon: "/overview-ai/icons/material-symbols_star-rounded.svg",
    title: "Hijab Bergo",
    price: "Rp55.000",
    oldPrice: "Rp99.000",
    heartIcon: "/overview-ai/icons/mdi_heart.svg",
    heartAlt: "Heart",
    reviews: 432,
    colorRecommendations: [
      { color: "bg-teal-600", border: "border-2 border-gray-300" },
      { color: "bg-blue-900" },
      { color: "bg-gray-800" },
    ],
    size: "XS-XXL",
    reason: "Perfect untuk bentuk wajah kotak dengan warna cool undertone",
  },
  {
    id: 5,
    image: "/hijab-8.jpg",
    match: "67% Match",
    matchIcon: "/overview-ai/icons/ai-generate.svg",
    matchAlt: "Heart",
    star: 4.6,
    starIcon: "/overview-ai/icons/material-symbols_star-rounded.svg",
    title: "Hijab Bergo",
    price: "Rp55.000",
    oldPrice: "Rp99.000",
    heartIcon: "/overview-ai/icons/mdi_heart.svg",
    heartAlt: "Heart",
    reviews: 432,
    colorRecommendations: [
      { color: "bg-teal-600", border: "border-2 border-gray-300" },
      { color: "bg-blue-900" },
      { color: "bg-gray-800" },
    ],
    size: "XS-XXL",
    reason: "Perfect untuk bentuk wajah kotak dengan warna cool undertone",
  },
  {
    id: 6,
    image: "/hijab-6.png",
    match: "67% Match",
    matchIcon: "/overview-ai/icons/ai-generate.svg",
    matchAlt: "Heart",
    star: 4.6,
    starIcon: "/overview-ai/icons/material-symbols_star-rounded.svg",
    title: "Hijab Bergo",
    price: "Rp55.000",
    oldPrice: "Rp99.000",
    heartIcon: "/overview-ai/icons/mdi_heart.svg",
    heartAlt: "Heart",
    reviews: 432,
    colorRecommendations: [
      { color: "bg-teal-600", border: "border-2 border-gray-300" },
      { color: "bg-blue-900" },
      { color: "bg-gray-800" },
    ],
    size: "XS-XXL",
    reason: "Perfect untuk bentuk wajah kotak dengan warna cool undertone",
  },
];